"""add_obsidian_integration

Revision ID: 73b8e2ee9147
Revises: 142c7808aebe
Create Date: 2026-05-22 13:32:22.459804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b8e2ee9147'
down_revision: Union[str, Sequence[str], None] = '142c7808aebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obsidian_tracked_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.add_column('articles', sa.Column('source', sa.String(length=20), nullable=False, server_default='manual'))
    op.add_column('articles', sa.Column('obsidian_file_path', sa.String(length=1000), nullable=True))
    op.add_column('articles', sa.Column('obsidian_file_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'obsidian_file_hash')
    op.drop_column('articles', 'obsidian_file_path')
    op.drop_column('articles', 'source')
    op.drop_table('obsidian_tracked_files')
    # ### end Alembic commands ###
