"""add input and output text to llm call logs

Revision ID: 7f6830cf4a29
Revises: 9779fc65a34a
Create Date: 2026-05-27 19:34:58.192699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6830cf4a29'
down_revision: Union[str, Sequence[str], None] = '9779fc65a34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call_logs', sa.Column('input_text', sa.Text(), nullable=True))
    op.add_column('llm_call_logs', sa.Column('output_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call_logs', 'output_text')
    op.drop_column('llm_call_logs', 'input_text')
    # ### end Alembic commands ###
